language: go
go:
  - 1.2
  - release
  - tip

install:
  - go get -d -t -v ./...

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

before_script:
  - ulimit -S -n 2048
  - sudo rethinkdb create --io-threads 2048
  - sudo rethinkdb --io-threads 2048 --daemon

script:
  - go test -v ./...
