language: go
go:
  - 1.2
  - release
  - tip

install:
  - go get -d -t -v ./...

before_script:
  - psql -c "CREATE DATABASE sesame_test;" -U postgres
  - psql -c "CREATE USER sesame WITH PASSWORD 'sesame';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE sesame_test TO sesame;" -U postgres

script:
  - go test -v ./...
